GROQ_API_KEY = "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"

SMTP_HOST = "smtp.gmail.com"
SMTP_PORT = 465
SMTP_USER = "migsnolimit26@gmail.com"
SMTP_PASS = "fbnyxgrmoregzghb"
FROM_EMAIL = "migsnolimit26@gmail.com"
MAIL_TO = "statetravel101@gmail.com"
DRIVE_PARENT_FOLDER_ID = "123qxwP5n3rVZdStoAFoeZES8P-vH68FM"
[GCP_SERVICE_ACCOUNT]
type = "service_account"
project_id = "api-key-testing-112603"
private_key_id = "e8c5498b017944359be91f1670237af0d17712bf"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDgh4GvO43xNmAT
kt+/iH4L6mgq2//qQtr6+DDZ0M6o+UC4PBeiuCkuX2VaJTUhsu5GksyUNVQIFXlB
QSy+O4/7Cx3Su2hlQ78SoSYcmSUbNd+wuaMm9dVvRzFdOOq4Xxp4rnLRs7oabP5J
9JnUxpFOqJ2NBuKTAWRoCNRm7d3y/itAbc4D8lgsvkNGOmwQihQmEOH7UCcNZlcl
h2qjBxi3712PqCwWhCndsDuLfRZcfqbEI3TFHjRB7vZbTIaB9Tzu9bKwSBsJLkbs
M8JQ3ZlY0PbWFmL4o2qJhgpoWVdAVivUrVwxPK4SNPpepShvCYU+dQuTPlnwBbBv
1wMOiaZdAgMBAAECggEAATn8RV7H6bdoUvMMcdlnBt2i8Aj/nuH6nEBa0/XGCzpB
VkBNyL/EydIPlax6W9LEZnJK18xqxxiG7wpSGj/tC2wGH66SZWs3Ufy7XpCfmUR0
El0RPRc+sTrsVBwJfDRYyqv5SJf4vkg2I2VIqdbj2FAnfCu7dR4e1EqoDl/iRH+I
Uic4YV2LEdWfCNrbgNrUlYdobmw/YwHB0ZrV+xJD9/rNKq9o1lirw5LUoeq0bWTm
+/uyQmV4seaGXUvKPXlsp8OveeGD0xDZvrINnGDtpozAhByE/+Q6FNh36Lk2XAHS
LDsvppONDIusdQ/9u0PANMkkLETlAN8/lRA6e0N9aQKBgQD2Z+/uazxDsHTAUwIk
hFoE99zPHRUv7uICGjPtoS2LacNvMokg4CMds037Wq2yKBySH4tUn+KDOiwRi2l1
mZ3RFT53yqZw7K48YR6Yum7bNByh748wYTCm19xTmS7Ji3f4/FjblpBwRmm407+O
tzG07odXFOfWqFIvwLD/raWwEwKBgQDpRYM2awAjO2+BLe8VspBIIVZtFvOX1MKr
T4GMzjAMajlpuauKrAElu9XybVnfINcVcJ8aW8WjLYDqqSl51f06X+hmHLMJhGtw
aOctkcGr7KPWbadMCmoz6QvbJCyjt5lsA7GMNyHIdAl3XM+Uh5Znhr3S8tktow1H
QSky7+19zwKBgG/FdfCQdCXARTV4ceBeqPbX+DF638F+esa5XBTOp/o1X5FxOwLO
qR8v1o/N8jx+NXeTF4CrhfRAzvymYJAXvp65JDzyj81pjx+UbmyZJPAKE3LhV/J6
I7eK80Z4leCWgzVOQoBZK+vCBPLyGlKChumryXiW4xNcBuviXGeePSpBAoGBAMyx
dqY11nUUHpBYYkfD3N+ugUxQq4g75ma06ZVJCNicDa08g863iHo4DVEhq48kHhhu
Lu7OQOsjbtB7iC2lHQQwTJnt7R0Y2b5WDyXplOzsRghPSFJtgSvz/7dYUuOGpFYo
F5BWgIqJaBUZl/1ZzR0jG0cUWoa1YV15TFGqP9f5AoGAL4jw3qnMRscaB3lbazla
Qj8pCuhSnMaqGa0l4LblrPp8VljmV7pElysE+Ne2/XnhqJF9+bWAEeytszMTbA4h
o90A1SM39x1NIITuyh3VSCxkPVWvP3iB8HMjumvkVX8nCN8S3gvpZV1MI/WOq13/
jIpAdrIKcC8Pw6oXJl4f6t8=
-----END PRIVATE KEY-----"""
client_email = "mobilsheets@api-key-testing-112603.iam.gserviceaccount.com"
client_id = "110798249678912444441"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/mobilsheets%40api-key-testing-112603.iam.gserviceaccount.com"
universe_domain = "googleapis.com"



DEBUG_SUBMISSION = true